### PR TITLE
[18.0][FW] sale_product_set: port PR from 14.0

### PR DESCRIPTION
**Pull request by natuan9**
There is PR in 14.0 that is not included. I created PR to port them to 18.0

Port PR: 
- `#3209`

### CODE REVIEW

**Comment by sbidoul** [comment]
@natuan9 didn't you mean to make your PR against the OCA repo? This is the acsone fork.

**Comment by natuan9** [comment]
Hi @sbidoul ,  I noticed that the PR` [18.0][MIG] sale_product_set` on OCA hasn't been reviewed yet. It would be more convenient if I create a PR to your branch `18.0-sale_product_set-sbj`.

**Comment by rousseldenis** [comment]
@sbejaoui

**Comment by sbejaoui** [comment]
> Hi @sbidoul , I noticed that the PR` [18.0][MIG] sale_product_set` on OCA hasn't been reviewed yet. It would be more convenient if I create a PR to your branch `18.0-sale_product_set-sbj`.

Thanks

**Pull request merged**
